# Generated by Django 4.1.5 on 2023-01-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainPhoto/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Главное фото',
                'verbose_name_plural': 'Главные фотографии',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('workTime', models.CharField(max_length=100, verbose_name='График работы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phoneNumber1', models.CharField(max_length=100, verbose_name='Телефон')),
                ('phoneNumber2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон2')),
                ('salesNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер Отдела продаж')),
                ('drugStoreNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер Аптеки')),
                ('siteLink', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('email', models.URLField(blank=True, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контакты Организации',
                'verbose_name_plural': 'Контакты Организаций',
            },
        ),
        migrations.CreateModel(
            name='TopBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topBlockPhoto/', verbose_name='Фото')),
                ('header', models.CharField(max_length=255, verbose_name='Название')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Вархний блок',
                'verbose_name_plural': 'Вархние блоки',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('organizationTitle', models.CharField(max_length=255, verbose_name='Загаловок над организаций')),
                ('mapLink', models.URLField(verbose_name='Ссылка на карту')),
                ('telegramLink', models.URLField(verbose_name='Ссылка на Telegram')),
                ('instagramLink', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('facebookLink', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('botShopLink', models.URLField(blank=True, null=True, verbose_name='Ссылка на Бот')),
                ('mainImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.mainimage', verbose_name='Верхние фотографии')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.organization', verbose_name='Контакты Организации')),
                ('topBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.topblock', verbose_name='Верхние Блоки')),
            ],
            options={
                'verbose_name': 'Страница Контакты',
                'verbose_name_plural': 'Страница Контакты',
            },
        ),
    ]
