# Generated by Django 4.1.5 on 2023-01-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemImage', models.ImageField(upload_to='item/', verbose_name='Картинка или иконка')),
                ('itemTitle', models.CharField(max_length=255, verbose_name='Название')),
                ('itemDescription', models.CharField(max_length=255, verbose_name='Описание')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.AlterModelOptions(
            name='mainimage',
            options={'verbose_name': 'Главная картинка', 'verbose_name_plural': 'Главные картинки'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Контакты организации', 'verbose_name_plural': 'Контакты организаций'},
        ),
        migrations.AlterField(
            model_name='contactinformation_page',
            name='mainImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.mainimage', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='contactinformation_page',
            name='topBlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.topblock', verbose_name='Верхний Блоки'),
        ),
        migrations.AlterField(
            model_name='topblock',
            name='image',
            field=models.ImageField(upload_to='topBlockPhoto/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovationheader', models.CharField(max_length=255, verbose_name='Название инновации')),
                ('innovationtitle', models.CharField(max_length=255, verbose_name='Заголовок инновации')),
                ('innovationsubtitle', models.TextField(verbose_name='Подзаголовок инновации')),
                ('innovationimage', models.ImageField(upload_to='InnovationPhoto/', verbose_name='Картинка инновации')),
                ('productionheader', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('productiontitle', models.CharField(max_length=255, verbose_name='Заголовок продукта')),
                ('productionsubtitle', models.TextField(verbose_name='Подзаголовок продукта')),
                ('productionimage', models.ImageField(upload_to='Main_PageProductionPhoto/', verbose_name='Фото Продукта')),
                ('productionBottonName', models.CharField(max_length=255, verbose_name='Название кнопки продукта')),
                ('whereToBuyheader', models.CharField(max_length=255, verbose_name='Название WhereToBuy')),
                ('whereToBuydescription', models.TextField(verbose_name='Подзаголовок WhereToBuy')),
                ('whereToBuyButtonName', models.CharField(max_length=255, verbose_name='Название кнопки WhereToBuy')),
                ('formButtonName', models.CharField(max_length=255, verbose_name='Название кнопки формы')),
                ('mainImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.mainimage', verbose_name='Главная фотография')),
                ('topBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.topblock', verbose_name='Верхний блок')),
            ],
            options={
                'verbose_name': 'Страница Контакты',
                'verbose_name_plural': 'Страница Контакты',
            },
        ),
    ]
