# Generated by Django 4.1.5 on 2023-01-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0002_differenceitem_alter_mainimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryIcon', models.ImageField(upload_to='category/', verbose_name='Фотография')),
                ('categoryName', models.CharField(max_length=255, verbose_name='Название')),
                ('categoryDescription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('imageField', models.ImageField(upload_to='product/', verbose_name='Изображение')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Фотография продукта',
                'verbose_name_plural': 'Фотографии продуктов',
            },
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterField(
            model_name='contactinformation_page',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='whereToBuyheader',
            field=models.TextField(max_length=255, verbose_name='Название WhereToBuy'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('productDescription', models.TextField(verbose_name='Описание продукта')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.category', verbose_name='Категория')),
                ('productImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.productimage', verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='InnovationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovationItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.differenceitem', verbose_name='Элеиенты')),
                ('mainImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.mainimage', verbose_name='Главная фотография')),
                ('topBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.topblock', verbose_name='Верхний блок')),
            ],
            options={
                'verbose_name': 'Страница инноваций',
                'verbose_name_plural': 'Страница инноваций',
            },
        ),
    ]
