# Generated by Django 4.1.5 on 2023-01-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0003_category_productimage_alter_mainpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differenceHeader', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('differenceTitle', models.CharField(max_length=255, verbose_name='Заголовок продукта')),
                ('scienceHeader', models.CharField(max_length=255, verbose_name='Название науки')),
                ('scienceDescription', models.CharField(max_length=255, verbose_name='Заголовок науки')),
                ('differenceItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample1', to='AORA.differenceitem', verbose_name='Наше отличие')),
                ('mainImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.mainimage', verbose_name='Главная фотография')),
                ('scienceItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample2', to='AORA.differenceitem', verbose_name='Нучный партнёр')),
                ('topBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AORA.topblock', verbose_name='Верхний блок')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
    ]
