# Generated by Django 4.1.5 on 2023-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0005_alter_aboutpage_scienceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationpage',
            name='innovationItem',
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='innovationItem',
            field=models.ManyToManyField(to='AORA.differenceitem', verbose_name='Элеиенты'),
        ),
    ]
