# Generated by Django 4.1.5 on 2023-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0007_alter_topblock_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topblock',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
