# Generated by Django 4.1.5 on 2023-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0008_alter_topblock_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topblock',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
