# Generated by Django 4.1.5 on 2023-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0009_alter_topblock_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='topBlock',
        ),
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='organization',
        ),
        migrations.AddField(
            model_name='contactinformation_page',
            name='organization',
            field=models.ManyToManyField(to='AORA.organization', verbose_name='Контакты Организации'),
        ),
    ]
