# Generated by Django 4.1.5 on 2023-01-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0012_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Slug'),
        ),
    ]
