# Generated by Django 4.1.5 on 2023-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.CharField(default='', max_length=255, verbose_name='Цена продукта'),
        ),
    ]
