# Generated by Django 4.1.5 on 2023-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0015_product_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('imageField', models.ImageField(upload_to='benefits/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Польза продукта',
                'verbose_name_plural': 'Пользы продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='beneficiosText',
            field=models.TextField(blank=True, null=True, verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='product',
            name='beneficiosItem',
            field=models.ManyToManyField(to='AORA.benefits', verbose_name='Польза продукта'),
        ),
    ]
