# Generated by Django 4.1.5 on 2023-01-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0017_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='topBlock',
        ),
        migrations.AddField(
            model_name='topblock',
            name='contactPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.contactinformation_page', verbose_name='Страница контакты'),
        ),
        migrations.AddField(
            model_name='topblock',
            name='mainPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.mainpage', verbose_name='Страница главная'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='contactPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.contactinformation_page', verbose_name='Страница контакты'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='mainPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.mainpage', verbose_name='Страница главная'),
        ),
    ]
