# Generated by Django 4.1.5 on 2023-01-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0020_alter_differenceitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationpage',
            name='innovationItem',
        ),
        migrations.AddField(
            model_name='differenceitem',
            name='innovationPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.innovationpage', verbose_name='Страница инноваций'),
        ),
        migrations.AddField(
            model_name='mainimage',
            name='innovationPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.innovationpage', verbose_name='Страница Инновации'),
        ),
    ]
