# Generated by Django 4.1.5 on 2023-01-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0021_remove_innovationpage_innovationitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Польза продукта', 'verbose_name_plural': 'Польза продуктов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='beneficiosItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImage',
        ),
        migrations.AddField(
            model_name='benefits',
            name='product',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.IntegerField(default='0', verbose_name='Цена продукта'),
        ),
    ]
