# Generated by Django 4.1.5 on 2023-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0022_alter_benefits_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topBlockImage', models.ImageField(null=True, upload_to='topBlockPhoto/', verbose_name='Верхний блок картинка')),
                ('topBlockHeader', models.CharField(blank=True, max_length=255, null=True, verbose_name='Верхний блок название')),
                ('topBlockTitle', models.CharField(max_length=255, null=True, verbose_name='Верхний блок заголовок')),
                ('topBlockSubtitle', models.TextField(null=True, verbose_name='Верхний блок подзаголовок')),
            ],
            options={
                'verbose_name': '- Страница продуктов',
                'verbose_name_plural': '- Страница продуктов',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='beneficiosText',
            field=models.TextField(blank=True, null=True, verbose_name='Beneficios текст'),
        ),
    ]
