# Generated by Django 4.1.5 on 2023-01-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0023_productspage_alter_product_beneficiostext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspage',
            name='topBlockHeader',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='topBlockImage',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='topBlockSubtitle',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='topBlockTitle',
        ),
        migrations.AddField(
            model_name='mainimage',
            name='productsPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.productspage', verbose_name='Страница Продуктов'),
        ),
        migrations.AddField(
            model_name='productspage',
            name='pageName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы'),
        ),
    ]
