# Generated by Django 4.1.5 on 2023-01-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0024_remove_productspage_topblockheader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='contactPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.contactinformation_page', verbose_name='Страница контакты'),
        ),
    ]
