# Generated by Django 4.1.5 on 2023-01-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0026_alter_aboutpage_differenceheader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='topBlockHeader',
        ),
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='topBlockImage',
        ),
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='topBlockSubtitle',
        ),
        migrations.RemoveField(
            model_name='contactinformation_page',
            name='topBlockTitle',
        ),
    ]
