# Generated by Django 4.1.5 on 2023-01-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0028_product_productmainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mechanismImage',
            field=models.ImageField(blank=True, null=True, upload_to='mecanism/', verbose_name='Картинка механизма действия'),
        ),
    ]
