# Generated by Django 4.1.5 on 2023-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0032_questionandanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='differenceTitle',
            field=models.TextField(verbose_name='Заголовок отличий'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='scienceDescription',
            field=models.TextField(verbose_name='Заголовок науки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='topBlockTitle',
            field=models.TextField(null=True, verbose_name='Верхний блок заголовок'),
        ),
        migrations.AlterField(
            model_name='contactinformation_page',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='differenceitem',
            name='itemDescription',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='whereToBuyheader',
            field=models.TextField(verbose_name='Название WhereToBuy'),
        ),
        migrations.AlterField(
            model_name='scienceitem',
            name='itemDescription',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
