# Generated by Django 4.1.5 on 2023-01-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0033_alter_aboutpage_differencetitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importantText', models.TextField(verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': '- Страница Важно',
                'verbose_name_plural': '- Страница Важно',
            },
        ),
        migrations.AddField(
            model_name='mainimage',
            name='importantPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.importantpage', verbose_name='Страница Важно'),
        ),
    ]
