# Generated by Django 4.1.5 on 2023-02-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0034_importantpage_mainimage_importantpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differenceitem',
            name='innovationPage',
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='integrationHeader',
            field=models.CharField(max_length=255, null=True, verbose_name='Название блока интеграций'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='integrationImage',
            field=models.ImageField(null=True, upload_to='innovationPageIntegrationPhoto/', verbose_name='Фото блока интеграций'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='integrationSubtitle',
            field=models.TextField(null=True, verbose_name='Подзаголовок блока интеграций'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='integrationTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока интеграций'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='productionBottonName',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки продукта'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='productionheader',
            field=models.CharField(max_length=255, null=True, verbose_name='Название создания продуктов'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='productionimage',
            field=models.ImageField(null=True, upload_to='innovationPageProductionPhoto/', verbose_name='Фото блока создания продуктов'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='productionsubtitle',
            field=models.TextField(null=True, verbose_name='Подзаголовок создания продуктов'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='productiontitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок создания продуктов'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='sienceCommunityHeader',
            field=models.CharField(max_length=255, null=True, verbose_name='Название блока научного сообщества'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='sienceCommunityImage',
            field=models.ImageField(null=True, upload_to='innovationPageProductionPhoto/', verbose_name='Фото блока научного сообщества'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='sienceCommunitySubtitle',
            field=models.TextField(null=True, verbose_name='Подзаголовок блока научного сообщества'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='sienceCommunityTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока научного сообщества'),
        ),
        migrations.AddField(
            model_name='scienceitem',
            name='innovationPage',
            field=models.ForeignKey(blank=True, editable=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AORA.innovationpage', verbose_name='Страница инноваций'),
        ),
    ]
