# Generated by Django 4.1.5 on 2023-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0035_remove_differenceitem_innovationpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation_page',
            name='sitenumber1',
            field=models.URLField(blank=True, null=True, verbose_name='Номер телефона сайта №1'),
        ),
        migrations.AddField(
            model_name='contactinformation_page',
            name='sitenumber2',
            field=models.URLField(blank=True, null=True, verbose_name='Номер телефона сайта №1'),
        ),
    ]
