# Generated by Django 4.1.5 on 2023-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0036_contactinformation_page_sitenumber1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation_page',
            name='sitenumber1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона сайта №1'),
        ),
        migrations.AlterField(
            model_name='contactinformation_page',
            name='sitenumber2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона сайта №2'),
        ),
    ]
