# Generated by Django 4.1.5 on 2023-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0040_remove_contactinformation_page_sitenumber2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='differenceHeader',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='differenceTitle',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='productionBottonName',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='productionheader',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='productionimage',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='productionsubtitle',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='productiontitle',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='productionBottonName',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кнопки продукта'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='productionheader',
            field=models.CharField(max_length=255, null=True, verbose_name='Название создания продуктов'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='productionimage',
            field=models.ImageField(null=True, upload_to='innovationPageProductionPhoto/', verbose_name='Фото блока создания продуктов'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='productionsubtitle',
            field=models.TextField(null=True, verbose_name='Подзаголовок создания продуктов'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='productiontitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок создания продуктов'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='differenceHeader',
            field=models.CharField(max_length=255, null=True, verbose_name='Название блока наше отличие'),
        ),
        migrations.AddField(
            model_name='innovationpage',
            name='differenceTitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока наше отличие'),
        ),
    ]
