# Generated by Django 4.1.5 on 2023-02-05 22:21

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0041_remove_aboutpage_differenceheader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='scienceDescription',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='scienceHeader',
        ),
        migrations.AlterField(
            model_name='importantpage',
            name='importantText',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст страницы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='beneficiosText',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Текст преимщества'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Информация о прродукте'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ'),
        ),
    ]
