# Generated by Django 4.1.5 on 2023-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0042_remove_aboutpage_sciencedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
