# Generated by Django 4.1.5 on 2023-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AORA', '0043_review_date_review_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
